version: "3.9"

services:
  db:
    image: postgres:13.3
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./.env

  web:
    build: .
    command: python manage.py runserver 127.0.0.1:8000
    volumes:
      - .:/usr/src/blog
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - db